### ISSUE TITLE
Invalid response

### ISSUE THREAD

**Issue by marcgarciamarti** [kalanda/homeassistant-aemet-sensor#10]
Hi,

I've followed the instructions and there is no way I can manage to make this integration to work. I keep getting this error:

```
[custom_components.aemet.AemetApi] Invalid response: 200 
```

prior to opening this issue, I've changed the API key and the Station to no avail.

Thanks

**Comment by kalanda** [comment]
You need to get your api_key and find the nearest station_id at https://opendata.aemet.es/ in order to finish the configuration.

IMPORTANT NOTE: You have to get the station_id from "Observación convencional" => "Datos de observación" stations. It isn't the same that in "Climatologías diarias".

**Comment by marcgarciamarti** [comment]
> You need to get your api_key and find the nearest station_id at https://opendata.aemet.es/ in order to finish the configuration.
> 
> IMPORTANT NOTE: You have to get the station_id from "Observación convencional" => "Datos de observación" stations. It isn't the same that in "Climatologías diarias".

Thanks for answering @kalanda ! I've done that already. I've actually even requested a new AP key prior to creating this issue.

This is my station id
```
aemet_station_id: 0076 (Barcelona Airport)
```
if you want I can share with you privately my API key. I'm at a loss.

**Comment by kalanda** [comment]
@marcgarciamarti I found the issue with the `station_id`. Almost all the station have some letters into the ID, but this one (0076) has only numbers and for some reason HA is transforming this number to string in a wrong way. Just wrap the station id value with double quotes and will work fine. I just test it with your station id.

**Comment by kalanda** [comment]
I mean like this:

```
sensor:
  - platform: aemet
    name: "BCN Airport"
    api_key: "your apikey"
    station_id: "0076"
    monitored_conditions:
      - temperature
      - humidity
      - pressure
      - precipitation
      - snow
      - visibility
      - wind_speed
      - wind_max_speed
      - wind_bearing
```
