### ISSUE TITLE
Forecast shown as "Unknown"

### ISSUE THREAD

**Issue by koldogut** [kalanda/homeassistant-aemet-sensor#21]
Sensors readings work fine but forecast info appears as "Unknown". Any additional config missing?

![aemet](https://user-images.githubusercontent.com/43078880/93782184-8cd7cb80-fc2a-11ea-8a8d-498ff70c5be3.JPG)

here is the code:

```
weather:
  - platform: aemet
    name: "AEMET"
    api_key: "eyJhbGciOiJIUzI1NiJ...."
    station_id: "XXXX"
```
